.TH "src Directory Reference" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBmaps\fP"
.br
.ti -1c
.RI "directory \fBscreens\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBattack\&.c\fP"
.br
.ti -1c
.RI "file \fBcamera\&.c\fP"
.br
.ti -1c
.RI "file \fBenemy\&.c\fP"
.br
.ti -1c
.RI "file \fBgame_loop\&.c\fP"
.br
.ti -1c
.RI "file \fBlevel\&.c\fP"
.br
.ti -1c
.RI "file \fBmain\&.c\fP"
.br
.ti -1c
.RI "file \fBmove_charac\&.c\fP"
.br
.ti -1c
.RI "file \fBplayer\&.c\fP"
.br
.ti -1c
.RI "file \fBprints\&.c\fP"
.br
.in -1c
