.TH "lib Directory Reference" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmy_snprintf\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_str_to_word_array\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcat\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_tabdup\&.c\fP"
.br
.in -1c
