.TH "src/maps Directory Reference" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/maps Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdestroy_maps\&.c\fP"
.br
.ti -1c
.RI "file \fBgenerate_maps\&.c\fP"
.br
.ti -1c
.RI "file \fBinit_maps\&.c\fP"
.br
.in -1c
