.TH "src/attack.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/attack.c
.SH SYNOPSIS
.br
.PP
\fC#include 'fita\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBattack\fP (\fBenemy_t\fP **enemies, \fBcursor_t\fP *defender, \fBenemy_t\fP *turn, \fBplayer_t\fP *player)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void attack (\fBenemy_t\fP ** enemies, \fBcursor_t\fP * defender, \fBenemy_t\fP * turn, \fBplayer_t\fP * player)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
