.TH "src/camera.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/camera.c
.SH SYNOPSIS
.br
.PP
\fC#include 'fita\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "enum \fBdirection\fP \fBborder_cam\fP (\fBcursor_t\fP *cam)"
.br
.ti -1c
.RI "void \fBcamera\fP (\fBplayer_t\fP *player, WINDOW *win, \fBmap_t\fP **maps)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "enum \fBdirection\fP border_cam (\fBcursor_t\fP * cam)"

.SS "void camera (\fBplayer_t\fP * player, WINDOW * win, \fBmap_t\fP ** maps)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
