.TH "charac_t" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
charac_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enemy\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlevel\fP"
.br
.ti -1c
.RI "int \fBhp\fP"
.br
.ti -1c
.RI "int \fBmp\fP"
.br
.ti -1c
.RI "int \fBstr\fP"
.br
.ti -1c
.RI "int \fBdef\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int def"

.SS "int hp"

.SS "int level"

.SS "int mp"

.SS "int str"


.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
