.TH "include/cursor.h" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/cursor.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcursor_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
