.TH "cursor_t" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cursor_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cursor\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
see cursor struct as a position's object these 'methods' shouldn't be touched 
.SH "Field Documentation"
.PP 
.SS "int x"

.SS "int y"


.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
