.TH "src/maps/destroy_maps.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/maps/destroy_maps.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'maps\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdestroy_maps\fP (\fBmap_t\fP **maps)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void destroy_maps (\fBmap_t\fP ** maps)"

.PP
\fBParameters:\fP
.RS 4
\fImaps\fP array 
.RE
.PP
\fBReturns:\fP
.RS 4
nothing  destroy each map 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
