.TH "enemy_t" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enemy_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <enemy\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBname\fP"
.br
.ti -1c
.RI "\fBcursor_t\fP \fBpos\fP"
.br
.ti -1c
.RI "\fBcursor_t\fP \fBpos_bak\fP"
.br
.ti -1c
.RI "\fBcharac_t\fP \fBcharac\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBcharac_t\fP charac"

.SS "char name"

.SS "\fBcursor_t\fP pos"

.SS "\fBcursor_t\fP pos_bak"


.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
