.TH "include/enemy.h" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/enemy.h
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcharac_t\fP"
.br
.ti -1c
.RI "struct \fBenemy_t\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBenemy_t\fP \fBplayer_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcreate_player\fP (\fBplayer_t\fP *player)"
.br
.ti -1c
.RI "void \fBenemy_turn\fP (\fBenemy_t\fP *player, \fBenemy_t\fP *enemy, char **map, \fBenemy_t\fP **enemies, char **state)"
.br
.ti -1c
.RI "void \fBassign_enemy\fP (char **map, char **old_state, \fBenemy_t\fP *enemy)"
.br
.ti -1c
.RI "void \fBadd_enemy\fP (\fBenemy_t\fP **enemies)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBenemy_t\fP \fBplayer_t\fP"

.SH "Function Documentation"
.PP 
.SS "void add_enemy (\fBenemy_t\fP ** enemies)"

.SS "void assign_enemy (char ** map, char ** old_state, \fBenemy_t\fP * enemy)"

.SS "void create_player (\fBplayer_t\fP * player)"

.PP
\fBParameters:\fP
.RS 4
\fIptr\fP to player_t 
.RE
.PP
\fBReturns:\fP
.RS 4
void  create player (assigning pointers as charac and pos) 
.RE
.PP

.SS "void enemy_turn (\fBenemy_t\fP * player, \fBenemy_t\fP * enemy, char ** map, \fBenemy_t\fP ** enemies, char ** state)"

.PP
\fBParameters:\fP
.RS 4
\fIcursor\fP ptr, \fBenemy_t\fP ptr, double char ptr 
.RE
.PP
\fBReturns:\fP
.RS 4
nothing  play the enemy turn 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
