.TH "src/game_loop.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/game_loop.c
.SH SYNOPSIS
.br
.PP
\fC#include <ncurses\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'fita\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBgame_loop\fP (\fBmap_t\fP **maps, char **old_state)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void game_loop (\fBmap_t\fP ** maps, char ** old_state)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
