.TH "src/level.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/level.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include 'fita\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBmap_t\fP ** \fBinit_level\fP (const char *path)"
.br
.ti -1c
.RI "void \fBdestroy_level\fP (\fBmap_t\fP **maps, char **old_state)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void destroy_level (\fBmap_t\fP ** maps, char ** old_state)"

.SS "\fBmap_t\fP** init_level (const char * path)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
