.TH "src/main.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'fita\&.h'\fP
.br
\fC#include 'my\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBusage\fP (char *error)"
.br
.ti -1c
.RI "int \fBmain\fP (int ac, char **av)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBm\fP = 'Usage:\\n\\t\&./fita\\nOption:\\n\\t%s\-\-generate\-maps %s%snumber\\n%s'"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int ac, char ** av)"

.SS "int usage (char * error)"

.SH "Variable Documentation"
.PP 
.SS "const char* m = 'Usage:\\n\\t\&./fita\\nOption:\\n\\t%s\-\-generate\-maps %s%snumber\\n%s'"
rudreais main 
.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
