.TH "md__r_e_a_d_m_e" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- Fed in the Abyss 
read the online wiki on \fCthe website\fP
.PP
.SS "want to help ?"
.PP
the branch \fCrefactoring\fP needs help ! fork and improve the actual code to make it smoother than it actually is, add comments, etc\&. any help is welcome !
.PP
.SS "trying it"
.PP
AFTER COMPILATION, IT IS MANDATORY TO RUN IT FROM (at least) THE PROJECT ROOT'S DIRECTORY ! 
