.TH "src/move_charac.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/move_charac.c
.SH SYNOPSIS
.br
.PP
\fC#include 'fita\&.h'\fP
.br
\fC#include 'enemy\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcursor_t\fP \fBmove_charac\fP (int key, \fBcursor_t\fP *pos, \fBcursor_t\fP *cam, char **map)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBcursor_t\fP move_charac (int key, \fBcursor_t\fP * pos, \fBcursor_t\fP * cam, char ** map)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
