.TH "include/my.h" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/my.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "Content< x\-color >< param > ForestGreen</param > char</x\-color > *< x\-color >< param > Blue1</param > \fBmy_strcat</x\-color >\fP (< x\-color >< param >ForestGreen</param >char</x\-color > *< x\-color >< param >sienna</param >dest</x\-color >,< x\-color >< param >ForestGreen</param >char</x\-color > *< x\-color >< param >sienna</param >src</x\-color >)"
.br
.ti -1c
.RI "< x\-color >< param > ForestGreen</param > char</x\-color > **< x\-color >< param > Blue1</param > \fBmy_tabdup</x\-color >\fP (< x\-color >< param >ForestGreen</param >char</x\-color > **< x\-color >< param >sienna</param >tab</x\-color >)"
.br
.ti -1c
.RI "< x\-color >< param > ForestGreen</param > char</x\-color > **< x\-color >< param > Blue1</param > \fBmy_str_to_word_array</x\-color >\fP (< x\-color >< param >ForestGreen</param >char</x\-color > *< x\-color >< param >sienna</param >line</x\-color >,< x\-color >< param >ForestGreen</param >char</x\-color >< x\-color >< param >sienna</param >delim</x\-color >)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "Content \fBType\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "<x\-color><param> ForestGreen</param> char</x\-color>**<x\-color><param> Blue1</param> \fBmy_str_to_word_array\fP</x\-color > (< x\-color >< param >ForestGreen</param >char</x\-color > *< x\-color >< param >sienna</param >line</x\-color >, < x\-color >< param >ForestGreen</param >char</x\-color >< x\-color >< param >sienna</param >delim</x\-color >)"

.SS "Content<x\-color><param> ForestGreen</param> char</x\-color>*<x\-color><param> Blue1</param> \fBmy_strcat\fP</x\-color > (< x\-color >< param >ForestGreen</param >char</x\-color > *< x\-color >< param >sienna</param >dest</x\-color >, < x\-color >< param >ForestGreen</param >char</x\-color > *< x\-color >< param >sienna</param >src</x\-color >)"

.SS "<x\-color><param> ForestGreen</param> char</x\-color>**<x\-color><param> Blue1</param> \fBmy_tabdup\fP</x\-color > (< x\-color >< param >ForestGreen</param >char</x\-color > **< x\-color >< param >sienna</param >tab</x\-color >)"

.SH "Variable Documentation"
.PP 
.SS "Content Type"

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
