.TH "lib/my_strcat.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my_strcat.c
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strcat\fP (char *dest, char *src)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strcat (char * dest, char * src)"
\fBmy_strcat()\fP function appends the src string and the dest string into a new string create using malloc(3)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdest\fP : pointer to first string 
.br
\fIsrc\fP : pointer to second string 
.RE
.PP
\fBReturns:\fP
.RS 4
A pointer to the new string\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
