.TH "lib/my_snprintf.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my_snprintf.c
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdarg\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_snprintf\fP (const char *format,\&.\&.\&.)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_snprintf (const char * format,  \&.\&.\&.)"
\fBmy_snprintf()\fP is a high-level implementation of snprintf(3)\&. It create output string with malloc(3)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIformat\fP : same format as printf(3) family 
.br
\fIva_arg\fP : argument list for format 
.RE
.PP
\fBReturns:\fP
.RS 4
Output string\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
