.TH "lib/my_str_to_word_array.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my_str_to_word_array.c
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char ** \fBmy_str_to_word_array\fP (char *line, char delim)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char** my_str_to_word_array (char * line, char delim)"
\fBmy_str_to_word_array()\fP function extract tokens from line by delim\&. The token array is created by malloc(3)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIline\fP : string to be parsed 
.br
\fIdelim\fP : delimiter with which line will be parsed 
.RE
.PP
\fBReturns:\fP
.RS 4
A array of tokens (NULL terminated)\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
