.TH "lib/my_str_to_word_array.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my_str_to_word_array.c
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBword_counter\fP (char *str, char delim)"
.br
.ti -1c
.RI "char * \fBget_word\fP (char *line, char delim)"
.br
.ti -1c
.RI "char ** \fBmy_str_to_word_array\fP (char *line, char delim)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* get_word (char * line, char delim)"

.SS "char** my_str_to_word_array (char * line, char delim)"

.SS "size_t word_counter (char * str, char delim)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
