.TH "lib/my_tabdup.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my_tabdup.c
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "size_t \fBmy_tablen\fP (char **tab)"
.br
.ti -1c
.RI "char ** \fBmy_tabdup\fP (char **tab)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char** my_tabdup (char ** tab)"

.SS "size_t my_tablen (char ** tab)"

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
