.TH "lib/my_tabdup.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my_tabdup.c
.SH SYNOPSIS
.br
.PP
\fC#include <assert\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char ** \fBmy_tabdup\fP (char **tab)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char** my_tabdup (char ** tab)"
\fBmy_tabdup()\fP function return a pointer to a new string array which is a duplicate of the string array tab\&. 
.PP
\fBParameters:\fP
.RS 4
\fItab\fP : A string array 
.RE
.PP
\fBReturns:\fP
.RS 4
A pointer to duplicated string array\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
