.TH "src/screens/player_info.c" 3 "Thu Aug 9 2018" "Version v0.3-alpha" "fed-in-the-abyss" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/screens/player_info.c
.SH SYNOPSIS
.br
.PP
\fC#include 'fita\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBscreen_charac\fP (\fBplayer_t\fP *player)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void screen_charac (\fBplayer_t\fP * player)"

.PP
\fBParameters:\fP
.RS 4
\fI\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for fed-in-the-abyss from the source code\&.
